### ISSUE TITLE
Cloudinary fails upload

### ISSUE THREAD

**Issue by ajonp** [njleonzhang/vscode-extension-mardown-image-paste#5]
Getting a failure when attempting cloudinary upload
<img width="437" alt="image" src="https://user-images.githubusercontent.com/3102249/49672476-41decb00-fa39-11e8-91a1-3e15acc2070e.png">
Here are my settings...is there more needed?
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3102249/49672644-ccbfc580-fa39-11e8-8ed3-5b91e5f27186.png">

**Comment by ajonp** [comment]
If you are logging errors, where can I find them? I don't see anything in my local...
/Users/ajonp/Library/Application Support/Code/logs/20181205T202054

**Comment by njleonzhang** [comment]
it  seems the cdn type 'cloudinary' not take effect, can you restart the vscode and try again.

**Comment by ajonp** [comment]
@njleonzhang it seems that you need to have electron server running prior to vscode launch (I think) This is the only way I have had success. Which is good enough for me! HUGE workflow improvement, thank you!

**Comment by njleonzhang** [comment]
@ajonp The plugin should start the electron server at the first time when you paster image. The issue you encountered may caused by the incorrect configuration when you start to configure the plugin. You can execute command `Paste Image: Reinit` to reinit the plugin. 😂  Anyway, it's great to know the plugin can help.
